BUILD_DIR="../../build/Client_List"

final:
	if [ ! -d $(BUILD_DIR) ];then mkdir -p $(BUILD_DIR);else rm -rf $(BUILD_DIR)/*;fi;
	cp ./encrypt_list.py $(BUILD_DIR)/encrypt_list.py
	cp ./o.enc $(BUILD_DIR)/o.enc
